// Copyright (C) 2026, Lux Partners Limited. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// aivm_gpu_engine_wgpu.cpp — WebGPU/WGSL driver for AIVMGPUEngine.
//
// Produces byte-identical roots to the CPU oracle and the Metal/CUDA backends
// by running the WGSL kernels in aivm_*.wgsl through a real WebGPU runtime
// (Dawn or wgpu-native — both expose the same `webgpu/webgpu.h` C ABI).
//
// Build: enabled by `LUX_AIVM_ENABLE_WGPU=ON`. The CMakeLists locates the
// runtime via find_path(webgpu.h) + find_library(wgpu_native|wgpu) and
// defines LUX_AIVM_HAS_WEBGPU when both are present. If the runtime is not
// available, this file compiles to a no-op factory that returns nullptr —
// tests then exercise the CPU-only path.
//
// Lifecycle notes:
//   * One persistent (Instance, Adapter, Device, Queue) — created lazily in
//     create_aivm_gpu_engine_wgpu().
//   * Per round: arena buffers (storage), op buffers (storage), uniform
//     buffers (count vec4u), result buffer (storage) + map-read staging.
//   * Each of the four kernels has a dedicated ShaderModule + Pipeline +
//     BindGroupLayout (extracted via wgpuComputePipelineGetBindGroupLayout
//     so the layout is auto-derived from the WGSL declarations).
//   * Kernels run with workgroup_size(1) and dispatchWorkgroups(1,1,1) —
//     this matches the CPU oracle's strict sequential semantics, which is
//     load-bearing for byte-equal cross-backend determinism.
//   * Drain async work via wgpuInstanceProcessEvents (modern API) and
//     wgpuDevicePoll (wgpu-native extension) — both safe to call.

#include "lux/aivm/aivm_gpu_engine.hpp"

#if defined(LUX_AIVM_HAS_WEBGPU)

#include <webgpu.h>
#if defined(LUX_AIVM_HAS_WGPU_NATIVE)
#  include <wgpu.h>
#endif

#include <atomic>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <memory>
#include <mutex>
#include <span>
#include <string>
#include <vector>

// WGSL sources — generated by CMake from src/aivm_*.wgsl into the build dir.
#include "aivm_wgsl_sources.h"

namespace aivm::gpu {

namespace {

// Workgroup constants must match the CUDA driver — kernels run serially
// (workgroup_size(1)), so the GPU produces the same insertion order as the
// CPU oracle even though the underlying hardware is parallel.
constexpr uint32_t kAttSlots       = kDefaultAttestationSlots;
constexpr uint32_t kModelSlots     = kDefaultModelSlots;
constexpr uint32_t kAnchorSlots    = kDefaultAnchorSlots;
constexpr uint32_t kMaxOpsPerRound = 4096u;

// 16-byte uniform: vec4<u32>. We pass per-arena counts in slot .x and zero
// elsewhere — matches `var<uniform> *_count_u: vec4<u32>` in the WGSL.
struct alignas(16) CountVec4 {
    uint32_t x = 0, y = 0, z = 0, w = 0;
};
static_assert(sizeof(CountVec4) == 16, "CountVec4 layout drift");

// Helpers --------------------------------------------------------------------

inline WGPUStringView sv(const char* s) {
    WGPUStringView v{};
    v.data = s;
    v.length = s == nullptr ? 0 : std::strlen(s);
    return v;
}
inline WGPUStringView sv(const std::string& s) {
    WGPUStringView v{};
    v.data = s.data();
    v.length = s.size();
    return v;
}

// Drive forward all in-flight async work. Both modern `webgpu.h` and the
// wgpu-native extension `wgpu.h` expose drainage; call both when available.
void drain(WGPUInstance instance, WGPUDevice device) {
    if (instance != nullptr) wgpuInstanceProcessEvents(instance);
#if defined(LUX_AIVM_HAS_WGPU_NATIVE)
    if (device != nullptr) wgpuDevicePoll(device, /*wait=*/WGPU_TRUE, nullptr);
#else
    (void)device;
#endif
}

// Block-on-buffer-map: returns true if the buffer is mapped successfully.
bool wait_map(WGPUInstance instance, WGPUDevice device,
              WGPUBuffer buffer, WGPUMapMode mode, size_t offset, size_t size)
{
    struct State {
        std::atomic<bool> done{false};
        WGPUMapAsyncStatus status{WGPUMapAsyncStatus_Error};
    } state;

    WGPUBufferMapCallbackInfo cb{};
    cb.mode = WGPUCallbackMode_AllowProcessEvents;
    cb.callback = [](WGPUMapAsyncStatus s, WGPUStringView /*msg*/,
                     void* u1, void* /*u2*/) {
        auto* st = static_cast<State*>(u1);
        st->status = s;
        st->done.store(true, std::memory_order_release);
    };
    cb.userdata1 = &state;
    cb.userdata2 = nullptr;

    WGPUFuture fut = wgpuBufferMapAsync(buffer, mode, offset, size, cb);
    (void)fut;
    for (int spin = 0; spin < 1024; ++spin) {
        if (state.done.load(std::memory_order_acquire)) break;
        drain(instance, device);
    }
    return state.done.load() && state.status == WGPUMapAsyncStatus_Success;
}

// ----------------------------------------------------------------------------
// Engine implementation
// ----------------------------------------------------------------------------

class AIVMGPUEngineWgpu final : public AIVMGPUEngine {
public:
    AIVMGPUEngineWgpu(WGPUInstance inst, WGPUAdapter adapter, WGPUDevice device,
                      WGPUQueue queue, std::string name)
        : instance_(inst),
          adapter_(adapter),
          device_(device),
          queue_(queue),
          device_name_(std::move(name))
    {
        build_pipelines();
    }

    ~AIVMGPUEngineWgpu() override {
        if (round_active()) end_round(round_.handle);
        release_pipelines();
        if (queue_)    wgpuQueueRelease(queue_);
        if (device_)   wgpuDeviceRelease(device_);
        if (adapter_)  wgpuAdapterRelease(adapter_);
        if (instance_) wgpuInstanceRelease(instance_);
    }

    const char* device_name() const override { return device_name_.c_str(); }
    bool round_active() const override { return round_.handle.valid(); }

    AIVMRoundHandle begin_round(const AIVMRoundDescriptor& desc) override {
        std::lock_guard<std::mutex> g(mu_);
        if (round_.handle.valid()) return AIVMRoundHandle{0};
        if (!device_ || !pipelines_built_) return AIVMRoundHandle{0};

        round_ = Round{};
        round_.desc = desc;
        round_.desc.attestation_op_count = 0;
        round_.desc.model_op_count       = 0;
        round_.desc.anchor_op_count      = 0;
        round_.host_att_ops.clear();
        round_.host_model_ops.clear();
        round_.host_anchor_ops.clear();

        if (!alloc_buffers()) {
            release_round_buffers();
            return AIVMRoundHandle{0};
        }
        round_.handle = AIVMRoundHandle{++next_handle_};
        return round_.handle;
    }

    void push_attestation_ops(AIVMRoundHandle h,
                              std::span<const AttestationOp> ops) override {
        std::lock_guard<std::mutex> g(mu_);
        if (!check_handle(h) || ops.empty()) return;
        uint32_t cap_left = kMaxOpsPerRound - round_.desc.attestation_op_count;
        uint32_t take = std::min<uint32_t>(uint32_t(ops.size()), cap_left);
        round_.host_att_ops.insert(round_.host_att_ops.end(),
                                   ops.begin(), ops.begin() + take);
        round_.desc.attestation_op_count += take;
    }

    void push_model_ops(AIVMRoundHandle h,
                        std::span<const ModelOp> ops) override {
        std::lock_guard<std::mutex> g(mu_);
        if (!check_handle(h) || ops.empty()) return;
        uint32_t cap_left = kMaxOpsPerRound - round_.desc.model_op_count;
        uint32_t take = std::min<uint32_t>(uint32_t(ops.size()), cap_left);
        round_.host_model_ops.insert(round_.host_model_ops.end(),
                                     ops.begin(), ops.begin() + take);
        round_.desc.model_op_count += take;
    }

    void push_anchor_ops(AIVMRoundHandle h,
                         std::span<const AnchorOp> ops) override {
        std::lock_guard<std::mutex> g(mu_);
        if (!check_handle(h) || ops.empty()) return;
        uint32_t cap_left = kMaxOpsPerRound - round_.desc.anchor_op_count;
        uint32_t take = std::min<uint32_t>(uint32_t(ops.size()), cap_left);
        round_.host_anchor_ops.insert(round_.host_anchor_ops.end(),
                                      ops.begin(), ops.begin() + take);
        round_.desc.anchor_op_count += take;
    }

    AIVMTransitionResult run_epoch(AIVMRoundHandle h) override {
        return run_until_done(h, 1);
    }

    AIVMTransitionResult run_until_done(AIVMRoundHandle h,
                                        std::size_t /*max_epochs*/) override {
        std::lock_guard<std::mutex> g(mu_);
        if (!check_handle(h)) return AIVMTransitionResult{};

        // -- 1. Upload desc + ops to device -----------------------------------
        wgpuQueueWriteBuffer(queue_, round_.desc_buf, 0, &round_.desc,
                             sizeof(AIVMRoundDescriptor));
        if (!round_.host_att_ops.empty()) {
            wgpuQueueWriteBuffer(queue_, round_.att_ops_buf, 0,
                                 round_.host_att_ops.data(),
                                 round_.host_att_ops.size() * sizeof(AttestationOp));
        }
        if (!round_.host_model_ops.empty()) {
            wgpuQueueWriteBuffer(queue_, round_.model_ops_buf, 0,
                                 round_.host_model_ops.data(),
                                 round_.host_model_ops.size() * sizeof(ModelOp));
        }
        if (!round_.host_anchor_ops.empty()) {
            wgpuQueueWriteBuffer(queue_, round_.anchor_ops_buf, 0,
                                 round_.host_anchor_ops.data(),
                                 round_.host_anchor_ops.size() * sizeof(AnchorOp));
        }
        // Count uniforms — arena sizes for in-kernel scans.
        CountVec4 att_count   { kAttSlots,    0, 0, 0 };
        CountVec4 model_count { kModelSlots,  0, 0, 0 };
        CountVec4 anchor_count{ kAnchorSlots, 0, 0, 0 };
        CountVec4 trans_count { kAttSlots, kModelSlots, kAnchorSlots, 0 };
        wgpuQueueWriteBuffer(queue_, round_.att_count_u,    0, &att_count,    sizeof(CountVec4));
        wgpuQueueWriteBuffer(queue_, round_.model_count_u,  0, &model_count,  sizeof(CountVec4));
        wgpuQueueWriteBuffer(queue_, round_.anchor_count_u, 0, &anchor_count, sizeof(CountVec4));
        wgpuQueueWriteBuffer(queue_, round_.trans_count_u,  0, &trans_count,  sizeof(CountVec4));

        // Zero per-kernel applied counters.
        uint32_t zero = 0;
        wgpuQueueWriteBuffer(queue_, round_.att_applied_buf,    0, &zero, sizeof(uint32_t));
        wgpuQueueWriteBuffer(queue_, round_.model_applied_buf,  0, &zero, sizeof(uint32_t));
        wgpuQueueWriteBuffer(queue_, round_.anchor_applied_buf, 0, &zero, sizeof(uint32_t));

        // -- 2. Build per-kernel bind groups ----------------------------------
        WGPUBindGroup bg_att   = make_att_bind_group();
        WGPUBindGroup bg_model = make_model_bind_group();
        WGPUBindGroup bg_anchor= make_anchor_bind_group();
        WGPUBindGroup bg_trans = make_trans_bind_group();
        if (!bg_att || !bg_model || !bg_anchor || !bg_trans) {
            if (bg_att)    wgpuBindGroupRelease(bg_att);
            if (bg_model)  wgpuBindGroupRelease(bg_model);
            if (bg_anchor) wgpuBindGroupRelease(bg_anchor);
            if (bg_trans)  wgpuBindGroupRelease(bg_trans);
            return AIVMTransitionResult{};
        }

        // -- 3. Encode dispatches ---------------------------------------------
        WGPUCommandEncoderDescriptor enc_d{};
        WGPUCommandEncoder enc = wgpuDeviceCreateCommandEncoder(device_, &enc_d);
        auto mode = static_cast<AIVMTransitionMode>(round_.desc.mode);

        auto dispatch = [&](WGPUComputePipeline pipe, WGPUBindGroup bg) {
            WGPUComputePassDescriptor pd{};
            WGPUComputePassEncoder pass = wgpuCommandEncoderBeginComputePass(enc, &pd);
            wgpuComputePassEncoderSetPipeline(pass, pipe);
            wgpuComputePassEncoderSetBindGroup(pass, 0, bg, 0, nullptr);
            wgpuComputePassEncoderDispatchWorkgroups(pass, 1, 1, 1);
            wgpuComputePassEncoderEnd(pass);
            wgpuComputePassEncoderRelease(pass);
        };

        if (mode == AIVMTransitionMode::AttestationApply ||
            mode == AIVMTransitionMode::FullRound) {
            dispatch(pipe_att_, bg_att);
        }
        if (mode == AIVMTransitionMode::ProvenanceApply ||
            mode == AIVMTransitionMode::FullRound) {
            dispatch(pipe_model_, bg_model);
        }
        if (mode == AIVMTransitionMode::AnchorApply ||
            mode == AIVMTransitionMode::FullRound) {
            dispatch(pipe_anchor_, bg_anchor);
        }
        // EpochTransition runs unconditionally — caller always wants roots.
        dispatch(pipe_trans_, bg_trans);

        // Copy result + applied counters into map-read staging buffers.
        wgpuCommandEncoderCopyBufferToBuffer(enc, round_.result_buf, 0,
            round_.result_staging, 0, sizeof(AIVMTransitionResult));
        wgpuCommandEncoderCopyBufferToBuffer(enc, round_.att_applied_buf,    0,
            round_.att_applied_staging,    0, sizeof(uint32_t));
        wgpuCommandEncoderCopyBufferToBuffer(enc, round_.model_applied_buf,  0,
            round_.model_applied_staging,  0, sizeof(uint32_t));
        wgpuCommandEncoderCopyBufferToBuffer(enc, round_.anchor_applied_buf, 0,
            round_.anchor_applied_staging, 0, sizeof(uint32_t));

        WGPUCommandBufferDescriptor cbd{};
        WGPUCommandBuffer cmd = wgpuCommandEncoderFinish(enc, &cbd);
        wgpuCommandEncoderRelease(enc);
        wgpuQueueSubmit(queue_, 1, &cmd);
        wgpuCommandBufferRelease(cmd);
        wgpuBindGroupRelease(bg_att);
        wgpuBindGroupRelease(bg_model);
        wgpuBindGroupRelease(bg_anchor);
        wgpuBindGroupRelease(bg_trans);

        // Drain submitted work before mapping.
        drain(instance_, device_);

        // -- 4. Read back result + applied counters ---------------------------
        AIVMTransitionResult out{};
        if (!read_back(round_.result_staging, sizeof(AIVMTransitionResult), &out)) {
            return AIVMTransitionResult{};
        }
        uint32_t att_app = 0, model_app = 0, anchor_app = 0;
        read_back(round_.att_applied_staging,    sizeof(uint32_t), &att_app);
        read_back(round_.model_applied_staging,  sizeof(uint32_t), &model_app);
        read_back(round_.anchor_applied_staging, sizeof(uint32_t), &anchor_app);
        out.attestation_apply_count = att_app;
        out.model_apply_count       = model_app;
        out.anchor_apply_count      = anchor_app;
        return out;
    }

    AIVMTransitionResult poll_round_result(AIVMRoundHandle h) const override {
        std::lock_guard<std::mutex> g(mu_);
        if (!check_handle(h)) return AIVMTransitionResult{};
        AIVMTransitionResult out{};
        if (!round_.result_staging) return out;
        // Caller is responsible for having already run the round; this poll
        // is non-fatal if the staging hasn't been refreshed yet.
        const_cast<AIVMGPUEngineWgpu*>(this)->read_back(
            round_.result_staging, sizeof(AIVMTransitionResult), &out);
        return out;
    }

    void end_round(AIVMRoundHandle h) override {
        std::lock_guard<std::mutex> g(mu_);
        if (!check_handle(h)) return;
        release_round_buffers();
        round_ = Round{};
    }

private:
    struct Round {
        AIVMRoundHandle handle{};
        AIVMRoundDescriptor desc{};

        std::vector<AttestationOp> host_att_ops;
        std::vector<ModelOp>       host_model_ops;
        std::vector<AnchorOp>      host_anchor_ops;

        WGPUBuffer desc_buf       = nullptr;
        WGPUBuffer att_ops_buf    = nullptr;
        WGPUBuffer model_ops_buf  = nullptr;
        WGPUBuffer anchor_ops_buf = nullptr;
        WGPUBuffer attestations_buf = nullptr;
        WGPUBuffer models_buf     = nullptr;
        WGPUBuffer anchors_buf    = nullptr;
        WGPUBuffer epoch_buf      = nullptr;
        WGPUBuffer result_buf     = nullptr;
        WGPUBuffer result_staging = nullptr;

        WGPUBuffer att_applied_buf    = nullptr;
        WGPUBuffer model_applied_buf  = nullptr;
        WGPUBuffer anchor_applied_buf = nullptr;
        WGPUBuffer att_applied_staging    = nullptr;
        WGPUBuffer model_applied_staging  = nullptr;
        WGPUBuffer anchor_applied_staging = nullptr;

        WGPUBuffer att_count_u    = nullptr;
        WGPUBuffer model_count_u  = nullptr;
        WGPUBuffer anchor_count_u = nullptr;
        WGPUBuffer trans_count_u  = nullptr;
    };

    bool check_handle(AIVMRoundHandle h) const {
        return h.valid() && h.opaque == round_.handle.opaque;
    }

    WGPUBuffer make_buf(uint64_t size, WGPUBufferUsage usage) {
        WGPUBufferDescriptor d{};
        d.size = size;
        d.usage = usage;
        d.mappedAtCreation = WGPU_FALSE;
        return wgpuDeviceCreateBuffer(device_, &d);
    }

    bool alloc_buffers() {
        constexpr WGPUBufferUsage kStorageUsage = static_cast<WGPUBufferUsage>(
            WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst | WGPUBufferUsage_CopySrc);
        constexpr WGPUBufferUsage kUniformUsage = static_cast<WGPUBufferUsage>(
            WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst);
        constexpr WGPUBufferUsage kStagingUsage = static_cast<WGPUBufferUsage>(
            WGPUBufferUsage_MapRead | WGPUBufferUsage_CopyDst);

        round_.desc_buf       = make_buf(sizeof(AIVMRoundDescriptor),       kStorageUsage);
        round_.att_ops_buf    = make_buf(sizeof(AttestationOp) * kMaxOpsPerRound, kStorageUsage);
        round_.model_ops_buf  = make_buf(sizeof(ModelOp)       * kMaxOpsPerRound, kStorageUsage);
        round_.anchor_ops_buf = make_buf(sizeof(AnchorOp)      * kMaxOpsPerRound, kStorageUsage);
        round_.attestations_buf = make_buf(sizeof(Attestation)        * kAttSlots,    kStorageUsage);
        round_.models_buf       = make_buf(sizeof(ModelRegistryEntry) * kModelSlots,  kStorageUsage);
        round_.anchors_buf      = make_buf(sizeof(AuditAnchor)        * kAnchorSlots, kStorageUsage);
        round_.epoch_buf  = make_buf(sizeof(AIVMEpochState),       kStorageUsage);
        round_.result_buf = make_buf(sizeof(AIVMTransitionResult), kStorageUsage);
        round_.result_staging = make_buf(sizeof(AIVMTransitionResult), kStagingUsage);

        round_.att_applied_buf    = make_buf(sizeof(uint32_t), kStorageUsage);
        round_.model_applied_buf  = make_buf(sizeof(uint32_t), kStorageUsage);
        round_.anchor_applied_buf = make_buf(sizeof(uint32_t), kStorageUsage);
        round_.att_applied_staging    = make_buf(sizeof(uint32_t), kStagingUsage);
        round_.model_applied_staging  = make_buf(sizeof(uint32_t), kStagingUsage);
        round_.anchor_applied_staging = make_buf(sizeof(uint32_t), kStagingUsage);

        round_.att_count_u    = make_buf(sizeof(CountVec4), kUniformUsage);
        round_.model_count_u  = make_buf(sizeof(CountVec4), kUniformUsage);
        round_.anchor_count_u = make_buf(sizeof(CountVec4), kUniformUsage);
        round_.trans_count_u  = make_buf(sizeof(CountVec4), kUniformUsage);

        return round_.desc_buf && round_.att_ops_buf && round_.model_ops_buf
            && round_.anchor_ops_buf && round_.attestations_buf
            && round_.models_buf && round_.anchors_buf && round_.epoch_buf
            && round_.result_buf && round_.result_staging
            && round_.att_applied_buf && round_.model_applied_buf
            && round_.anchor_applied_buf && round_.att_applied_staging
            && round_.model_applied_staging && round_.anchor_applied_staging
            && round_.att_count_u && round_.model_count_u
            && round_.anchor_count_u && round_.trans_count_u;
    }

    void release_round_buffers() {
#define REL(b) if (round_.b) { wgpuBufferRelease(round_.b); round_.b = nullptr; }
        REL(desc_buf);
        REL(att_ops_buf); REL(model_ops_buf); REL(anchor_ops_buf);
        REL(attestations_buf); REL(models_buf); REL(anchors_buf);
        REL(epoch_buf); REL(result_buf); REL(result_staging);
        REL(att_applied_buf); REL(model_applied_buf); REL(anchor_applied_buf);
        REL(att_applied_staging); REL(model_applied_staging); REL(anchor_applied_staging);
        REL(att_count_u); REL(model_count_u); REL(anchor_count_u); REL(trans_count_u);
#undef REL
    }

    // ------------------------------------------------------------------
    // Pipelines & shader modules — one set for the engine's lifetime.
    // ------------------------------------------------------------------

    WGPUShaderModule make_module(const std::string& src) {
        WGPUShaderSourceWGSL wgsl{};
        wgsl.chain.next = nullptr;
        wgsl.chain.sType = WGPUSType_ShaderSourceWGSL;
        wgsl.code = sv(src);
        WGPUShaderModuleDescriptor d{};
        d.nextInChain = &wgsl.chain;
        return wgpuDeviceCreateShaderModule(device_, &d);
    }

    WGPUComputePipeline make_pipe(WGPUShaderModule m, const char* entry) {
        WGPUComputePipelineDescriptor d{};
        d.compute.module = m;
        d.compute.entryPoint = sv(entry);
        d.layout = nullptr; // auto layout — derived from WGSL bindings.
        return wgpuDeviceCreateComputePipeline(device_, &d);
    }

    void build_pipelines() {
        const std::string common(kAIVMWGSL_Common);
        // The WGSL kernel files start with `@group(0) @binding(...)` and use
        // shared types from common. Concatenation of "common + kernel" yields
        // a complete WGSL source per kernel.
        std::string src_att      = common + std::string(kAIVMWGSL_Attestation);
        std::string src_model    = common + std::string(kAIVMWGSL_Provenance);
        std::string src_anchor   = common + std::string(kAIVMWGSL_Anchor);
        std::string src_trans    = common + std::string(kAIVMWGSL_Transition);

        mod_att_    = make_module(src_att);
        mod_model_  = make_module(src_model);
        mod_anchor_ = make_module(src_anchor);
        mod_trans_  = make_module(src_trans);
        if (!mod_att_ || !mod_model_ || !mod_anchor_ || !mod_trans_) return;

        pipe_att_    = make_pipe(mod_att_,    "aivm_attestation_apply");
        pipe_model_  = make_pipe(mod_model_,  "aivm_provenance_apply");
        pipe_anchor_ = make_pipe(mod_anchor_, "aivm_anchor_apply");
        pipe_trans_  = make_pipe(mod_trans_,  "aivm_epoch_transition");
        if (!pipe_att_ || !pipe_model_ || !pipe_anchor_ || !pipe_trans_) return;

        bgl_att_    = wgpuComputePipelineGetBindGroupLayout(pipe_att_, 0);
        bgl_model_  = wgpuComputePipelineGetBindGroupLayout(pipe_model_, 0);
        bgl_anchor_ = wgpuComputePipelineGetBindGroupLayout(pipe_anchor_, 0);
        bgl_trans_  = wgpuComputePipelineGetBindGroupLayout(pipe_trans_, 0);
        if (!bgl_att_ || !bgl_model_ || !bgl_anchor_ || !bgl_trans_) return;

        pipelines_built_ = true;
    }

    void release_pipelines() {
#define REL(x) if (x) { wgpuBindGroupLayoutRelease(x); x = nullptr; }
        REL(bgl_att_); REL(bgl_model_); REL(bgl_anchor_); REL(bgl_trans_);
#undef REL
#define REL(x) if (x) { wgpuComputePipelineRelease(x); x = nullptr; }
        REL(pipe_att_); REL(pipe_model_); REL(pipe_anchor_); REL(pipe_trans_);
#undef REL
#define REL(x) if (x) { wgpuShaderModuleRelease(x); x = nullptr; }
        REL(mod_att_); REL(mod_model_); REL(mod_anchor_); REL(mod_trans_);
#undef REL
    }

    // ------------------------------------------------------------------
    // Bind-group construction — one per kernel, per round.
    // ------------------------------------------------------------------

    static WGPUBindGroupEntry buf_entry(uint32_t binding, WGPUBuffer b, uint64_t size) {
        WGPUBindGroupEntry e{};
        e.binding = binding;
        e.buffer = b;
        e.offset = 0;
        e.size = size;
        return e;
    }

    WGPUBindGroup make_att_bind_group() {
        WGPUBindGroupEntry e[5] = {
            buf_entry(0, round_.desc_buf,         sizeof(AIVMRoundDescriptor)),
            buf_entry(1, round_.att_ops_buf,      sizeof(AttestationOp) * kMaxOpsPerRound),
            buf_entry(2, round_.attestations_buf, sizeof(Attestation)   * kAttSlots),
            buf_entry(3, round_.att_applied_buf,  sizeof(uint32_t)),
            buf_entry(4, round_.att_count_u,      sizeof(CountVec4)),
        };
        WGPUBindGroupDescriptor d{};
        d.layout = bgl_att_;
        d.entryCount = 5;
        d.entries = e;
        return wgpuDeviceCreateBindGroup(device_, &d);
    }
    WGPUBindGroup make_model_bind_group() {
        WGPUBindGroupEntry e[5] = {
            buf_entry(0, round_.desc_buf,          sizeof(AIVMRoundDescriptor)),
            buf_entry(1, round_.model_ops_buf,     sizeof(ModelOp) * kMaxOpsPerRound),
            buf_entry(2, round_.models_buf,        sizeof(ModelRegistryEntry) * kModelSlots),
            buf_entry(3, round_.model_applied_buf, sizeof(uint32_t)),
            buf_entry(4, round_.model_count_u,     sizeof(CountVec4)),
        };
        WGPUBindGroupDescriptor d{};
        d.layout = bgl_model_;
        d.entryCount = 5;
        d.entries = e;
        return wgpuDeviceCreateBindGroup(device_, &d);
    }
    WGPUBindGroup make_anchor_bind_group() {
        WGPUBindGroupEntry e[5] = {
            buf_entry(0, round_.desc_buf,           sizeof(AIVMRoundDescriptor)),
            buf_entry(1, round_.anchor_ops_buf,     sizeof(AnchorOp) * kMaxOpsPerRound),
            buf_entry(2, round_.anchors_buf,        sizeof(AuditAnchor) * kAnchorSlots),
            buf_entry(3, round_.anchor_applied_buf, sizeof(uint32_t)),
            buf_entry(4, round_.anchor_count_u,     sizeof(CountVec4)),
        };
        WGPUBindGroupDescriptor d{};
        d.layout = bgl_anchor_;
        d.entryCount = 5;
        d.entries = e;
        return wgpuDeviceCreateBindGroup(device_, &d);
    }
    WGPUBindGroup make_trans_bind_group() {
        WGPUBindGroupEntry e[7] = {
            buf_entry(0, round_.desc_buf,         sizeof(AIVMRoundDescriptor)),
            buf_entry(1, round_.attestations_buf, sizeof(Attestation)        * kAttSlots),
            buf_entry(2, round_.models_buf,       sizeof(ModelRegistryEntry) * kModelSlots),
            buf_entry(3, round_.anchors_buf,      sizeof(AuditAnchor)        * kAnchorSlots),
            buf_entry(4, round_.epoch_buf,        sizeof(AIVMEpochState)),
            buf_entry(5, round_.result_buf,       sizeof(AIVMTransitionResult)),
            buf_entry(6, round_.trans_count_u,    sizeof(CountVec4)),
        };
        WGPUBindGroupDescriptor d{};
        d.layout = bgl_trans_;
        d.entryCount = 7;
        d.entries = e;
        return wgpuDeviceCreateBindGroup(device_, &d);
    }

    // ------------------------------------------------------------------
    // Synchronous map-read of a staging buffer into host memory.
    // ------------------------------------------------------------------
    bool read_back(WGPUBuffer staging, size_t size, void* dst) {
        if (!wait_map(instance_, device_, staging, WGPUMapMode_Read, 0, size)) {
            return false;
        }
        const void* mapped = wgpuBufferGetConstMappedRange(staging, 0, size);
        if (!mapped) {
            wgpuBufferUnmap(staging);
            return false;
        }
        std::memcpy(dst, mapped, size);
        wgpuBufferUnmap(staging);
        return true;
    }

private:
    WGPUInstance instance_  = nullptr;
    WGPUAdapter  adapter_   = nullptr;
    WGPUDevice   device_    = nullptr;
    WGPUQueue    queue_     = nullptr;
    std::string  device_name_;

    bool pipelines_built_ = false;
    WGPUShaderModule    mod_att_ = nullptr,   mod_model_ = nullptr,   mod_anchor_ = nullptr,   mod_trans_ = nullptr;
    WGPUComputePipeline pipe_att_ = nullptr,  pipe_model_ = nullptr,  pipe_anchor_ = nullptr,  pipe_trans_ = nullptr;
    WGPUBindGroupLayout bgl_att_ = nullptr,   bgl_model_ = nullptr,   bgl_anchor_ = nullptr,   bgl_trans_ = nullptr;

    Round round_;
    uint64_t next_handle_ = 0;
    mutable std::mutex mu_;
};

// ----------------------------------------------------------------------------
// Adapter/Device acquisition — synchronous bring-up.
// ----------------------------------------------------------------------------

WGPUAdapter request_adapter_sync(WGPUInstance inst) {
    struct State {
        std::atomic<bool> done{false};
        WGPUAdapter adapter{nullptr};
    } state;
    WGPURequestAdapterOptions opts{};
    opts.powerPreference = WGPUPowerPreference_HighPerformance;

    WGPURequestAdapterCallbackInfo cb{};
    cb.mode = WGPUCallbackMode_AllowProcessEvents;
    cb.callback = [](WGPURequestAdapterStatus status, WGPUAdapter a,
                     WGPUStringView /*msg*/, void* u1, void* /*u2*/) {
        auto* s = static_cast<State*>(u1);
        if (status == WGPURequestAdapterStatus_Success) s->adapter = a;
        s->done.store(true, std::memory_order_release);
    };
    cb.userdata1 = &state;
    WGPUFuture fut = wgpuInstanceRequestAdapter(inst, &opts, cb);
    (void)fut;
    for (int spin = 0; spin < 1024 && !state.done.load(); ++spin) {
        wgpuInstanceProcessEvents(inst);
    }
    return state.adapter;
}

WGPUDevice request_device_sync(WGPUInstance inst, WGPUAdapter adapter) {
    struct State {
        std::atomic<bool> done{false};
        WGPUDevice device{nullptr};
    } state;
    WGPUDeviceDescriptor desc{};

    WGPURequestDeviceCallbackInfo cb{};
    cb.mode = WGPUCallbackMode_AllowProcessEvents;
    cb.callback = [](WGPURequestDeviceStatus status, WGPUDevice d,
                     WGPUStringView /*msg*/, void* u1, void* /*u2*/) {
        auto* s = static_cast<State*>(u1);
        if (status == WGPURequestDeviceStatus_Success) s->device = d;
        s->done.store(true, std::memory_order_release);
    };
    cb.userdata1 = &state;
    WGPUFuture fut = wgpuAdapterRequestDevice(adapter, &desc, cb);
    (void)fut;
    for (int spin = 0; spin < 1024 && !state.done.load(); ++spin) {
        wgpuInstanceProcessEvents(inst);
    }
    return state.device;
}

}  // anonymous namespace

std::unique_ptr<AIVMGPUEngine> create_aivm_gpu_engine_wgpu()
{
    WGPUInstanceDescriptor inst_d{};
    WGPUInstance inst = wgpuCreateInstance(&inst_d);
    if (!inst) return nullptr;

    WGPUAdapter adapter = request_adapter_sync(inst);
    if (!adapter) {
        wgpuInstanceRelease(inst);
        return nullptr;
    }
    WGPUDevice device = request_device_sync(inst, adapter);
    if (!device) {
        wgpuAdapterRelease(adapter);
        wgpuInstanceRelease(inst);
        return nullptr;
    }
    WGPUQueue queue = wgpuDeviceGetQueue(device);
    if (!queue) {
        wgpuDeviceRelease(device);
        wgpuAdapterRelease(adapter);
        wgpuInstanceRelease(inst);
        return nullptr;
    }

    return std::unique_ptr<AIVMGPUEngine>(
        new AIVMGPUEngineWgpu(inst, adapter, device, queue, "wgpu-native"));
}

}  // namespace aivm::gpu

#else  // !LUX_AIVM_HAS_WEBGPU

namespace aivm::gpu {

std::unique_ptr<AIVMGPUEngine> create_aivm_gpu_engine_wgpu()
{
    return nullptr;
}

}  // namespace aivm::gpu

#endif  // LUX_AIVM_HAS_WEBGPU

// Default factory — wired by the platform (Metal first on Apple, CUDA on
// Linux). When neither is enabled and WGPU is, this is the lone backend.
#if !defined(__APPLE__) && !defined(LUX_AIVM_HAS_CUDA) && defined(LUX_AIVM_HAS_WEBGPU)
namespace aivm::gpu {
std::unique_ptr<AIVMGPUEngine> AIVMGPUEngine::create() {
    return create_aivm_gpu_engine_wgpu();
}
}
#endif
